package(default_visibility = ["//visibility:public"])

#load("//@bazel/jasmine:index.bzl", "jasmine_node_test")
#load("@npm_bazel_jasmine//:index.bzl", "jasmine_node_test")

#jasmine_node_test(
#    name = "base",
#    srcs = glob(["*_spec.js"]),
#    deps = [],
#)
