package(default_visibility = ["//visibility:public"])

load("@build_bazel_rules_nodejs//:defs.bzl", "jasmine_node_test")

jasmine_node_test(
    name = "base",
    srcs = glob(["*_spec.js"]),
    deps = [],
)
