package(default_visibility = ["//visibility:public"])

exports_files([
    "_all.pug",
    "acordeon.pug",
    "breadcrumb.pug",
    "card.pug",
    "group.pug",
    "media.pug",
    "mega.pug",
    "menus.pug",
    "message.pug",
    "modal.pug",
    "navbar.pug",
    "notify.pug",
    "slideshow.pug",
    "social.pug",
    "table.pug",
    "tabs.pug",
])
