#load("@npm_bazel_typescript//:index.bzl", "ts_library")
load("@npm//@bazel/typescript:index.bzl", "ts_library")
#load("@npm//@bazel/typescript:index.bzl", "ts_library")

ts_library(
    name = "main",
    srcs = ["main.ts"],
    deps = [
        "@npm//@types/jquery",
        "@npm//jquery",
    ],
)
