package(default_visibility = ["//visibility:public"])

exports_files([
    "_all.pug",
    "blockquote.pug",
    "box.pug",
    "buttons.pug",
    "chip.pug",
    "dropdown.pug",
    "icons.pug",
    "preload.pug",
    "progress.pug",
    "range.pug",
    "tags.pug",
    "toggle.pug",
    "tooltip.pug",
])
