package(default_visibility = ["//visibility:public"])

exports_files([
    "_all.pug",
    "_anim.pug",
    "_colors.pug",
    "_contenido.pug",
    "_functions.pug",
    "_home.pug",
    "_introduccion.pug",
    "_mixins.pug",
    "_modular.pug",
    "_typography.pug",
    "features.pug",
    "portafolio.pug",
])
