package(default_visibility = ["//visibility:public"])

exports_files([
    "_all.pug",
    "checkbox.pug",
    "color.pug",
    "field.pug",
    "input.pug",
    "radio.pug",
    "select.pug",
    "textarea.pug",
])
