package(default_visibility = ["//visibility:public"])

#load("@npm_bazel_typescript//:index.bzl", "ts_library")
#load("//@bazel/typescript:index.bzl", "ts_project")
load("@npm//@bazel/typescript:index.bzl", "ts_library")

ts_library(
    name = "kimerajs",
    srcs = ["source.ts"],
)
